spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


app:
  jwt:
    secret: ${JWT_SECRET:railway-fallback-secret-only-for-hackathon}

  file:
    upload-dir: ${UPLOAD_DIR:/app/uploads}

logging:
  level:
    root: INFO
    com.incident: INFO

